[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[lib]
name = "sudoku"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.31"
csv = "1.3.0"
itertools = "0.12.0"
rand = "0.8.5"
rayon = "1.8.0"
